name: Cache & Install Dependencies
description: Cache & Install Dependencies
inputs:
  caching:
    description: Whether to cache dependencies or not.
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Cache node_modules
      if: inputs.caching == 'true'
      uses: actions/cache@v3
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash